arb-dir: lib/l10n
template-arb-file: app_en.arb
output-dir: lib/generated
output-localization-file: app_localizations.dart
use-deferred-loading: true
synthetic-package: false
output-class: "InsightOfYouAppLocalizations"